apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: reddog.config
  namespace: reddog
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://otel-collector.default.svc.cluster.local:9411/api/v2/spans"